language: python

python: 3.5

env:
  global:
    - DATABASE_URL: postgresql://postgres@127.0.0.1:5432/channels_example

cache:
  pip: true
  directories:
    - node_modules # NPM packages

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - npm install

before_script:
  - psql -c 'create database channels_example;' -U postgres

script: BROWSER_TYPE=phantomjs ./manage.py harvest -v 3
